// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DAL.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20180821130728_modelCliente")]
    partial class modelCliente
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            

            modelBuilder.Entity("DAL.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CPF")
                        .HasMaxLength(15);

                    b.Property<string>("Cep")
                        .HasMaxLength(10);

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Email")
                        .HasMaxLength(50);

                    b.Property<string>("Endereco")
                        .HasMaxLength(100);

                    b.Property<int>("Idade");

                    b.Property<string>("Instagram")
                        .HasMaxLength(50);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Observacao");

                    b.Property<string>("Profissao")
                        .HasMaxLength(30);

                    b.Property<string>("Sexo")
                        .HasMaxLength(15);

                    b.Property<string>("TelCel")
                        .HasMaxLength(16);

                    b.Property<string>("TelRes")
                        .HasMaxLength(16);

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            
#pragma warning restore 612, 618
        }
    }
}
